apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:
    app: web
    region: US
    team: test
spec:
  containers:
    - name: "c1"
      image: "vimal13/apache-webserver-php"








# Reference for selectors also
